name: Integration Checks
on:
  push:
    branches-ignore:
      - main
      - develop
jobs:
  integration:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Npm install
        run: npm i --force
      - name: QA Review
        run: |
          npm run lint
          npm run format:check
